module_separator = ""
reset_color = true

[bookmarks]
search_depth = 0
exclude = []

[[module]]
type = "Symbol"
symbol = ""
color = "White"

# [[module]]
# disabled = true
# type = "Bookmarks"
# separator = " "
# color = "White"
# behind_symbol = "â‡¡"
# surround_with_quotes = true

[[module]]
type = "Commit"
max_length = 24
empty_text = ""
surround_with_quotes = true
surround_with_quotes_when_empty = false

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = " (conflict)"
color = "Red"

[module.divergent]
disabled = false
text = " (divergent)"
color = "Cyan"

[module.empty]
disabled = false
text = "[0]"
color = "White"

[module.immutable]
disabled = false
text = " (immutable)"
color = "Yellow"

[module.hidden]
disabled = false
text = " (hidden)"
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed}{added}{removed}]"
color = "White"
disabled = true
hide_if_empty = true

[module.changed_files]
prefix = "~"
suffix = ""
color = "White"

[module.added_lines]
prefix = "+"
suffix = ""
color = "White"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "White"


